"""empty message

Revision ID: 71adfbef578f
Revises: c438d51c435b
Create Date: 2018-12-16 02:18:25.665427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71adfbef578f'
down_revision = 'c438d51c435b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_address'), 'employee', ['address'], unique=True)
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=True)
    op.add_column('contract', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.drop_index('ix_contract_employee', table_name='contract')
    op.create_foreign_key(None, 'contract', 'employee', ['employee_id'], ['id'])
    op.drop_column('contract', 'phone')
    op.drop_column('contract', 'employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('employee', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contract', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.create_index('ix_contract_employee', 'contract', ['employee'], unique=True)
    op.drop_column('contract', 'employee_id')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_index(op.f('ix_employee_address'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
