"""empty message

Revision ID: c438d51c435b
Revises: c2bab96a51de
Create Date: 2018-12-15 04:03:09.951240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c438d51c435b'
down_revision = 'c2bab96a51de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('date_sign', sa.DateTime(), nullable=False),
    sa.Column('date_effective', sa.DateTime(), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('employee', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_employee'), 'contract', ['employee'], unique=True)
    op.create_index(op.f('ix_contract_title'), 'contract', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_title'), table_name='contract')
    op.drop_index(op.f('ix_contract_employee'), table_name='contract')
    op.drop_table('contract')
    # ### end Alembic commands ###
